-- Migration: add_target_company_id_to_self_reg
-- ID: ARCH-20260624-03
-- Date: 2026-06-24
-- Generated by: SOFIA (initial) + INTEGRA (handwritten, idempotent due to drift in local DB)
--
-- PURPOSE:
--   Añadir campo targetCompanyId (FK opcional a companies) a
--   company_self_registrations para soportar la vía de "completar
--   datos de empresa existente" vía link externo.
--
-- IDEMPOTENT:
--   Usa IF NOT EXISTS / EXISTS() para todas las sentencias, de modo
--   que pueda ejecutarse múltiples veces sin error (útil para
--   sincronizar DB local con estado consolidado de Railway).
--
-- EQUIVALENTE A:
--   context/infra/05-migration-20260624-target-company-self-reg.sql
--   (script para aplicar manualmente en Railway Query)

-- 1. Columna targetCompanyId
ALTER TABLE "company_self_registrations"
  ADD COLUMN IF NOT EXISTS "targetCompanyId" TEXT;

-- 2. Índice
CREATE INDEX IF NOT EXISTS "company_self_registrations_targetCompanyId_idx"
  ON "company_self_registrations"("targetCompanyId");

-- 3. Foreign key
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'company_self_registrations_targetCompanyId_fkey'
      AND table_name = 'company_self_registrations'
  ) THEN
    ALTER TABLE "company_self_registrations"
      ADD CONSTRAINT "company_self_registrations_targetCompanyId_fkey"
      FOREIGN KEY ("targetCompanyId") REFERENCES "companies"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
